In [3]:
import numpy as np

In [2]:
import time

In [6]:
time.time()/60/60/24/365 #how many years from 1970

53.28612266313793

In [31]:
size = 10000000
l1 = range(size)
l2 = range(size)

result= []
start_time = time.time()
for x,y in zip(l1,l2):
    result.append(x+y)
    
end_time = time.time()

print(end_time - start_time)

2.7414138317108154


In [24]:
start_time = time.time()
size = 10000000
a1 = np.arange(size)
a2 = np.arange(size)

result = a1 +a2
end_time = time.time()

print(end_time - start_time)

0.08595442771911621


In [32]:
a = [1,2,3,4]
b = [4,5,6,7]
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
result


[5, 7, 9, 11]

In [34]:
a1 = np.array(a)
b1 = np.array(b)
print(a1)
print(b1)

[1 2 3 4]
[4 5 6 7]


In [35]:
a1 * b1

array([ 4, 10, 18, 28])

In [36]:
a1 / b1

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [39]:
my_list2 = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
myarray = np.array(my_list2)
myarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
myarray.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.resize(myarray,(5,3))

In [42]:
myarray.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [43]:
myarray.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
liste = list(range(15))
liste

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [46]:
arr2 = np.array((liste), ndmin=6)
arr2

array([[[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
            14]]]]]])

In [47]:
arr2.ndim

6

In [48]:
arr2.dtype

dtype('int32')

In [52]:
new_x = my_float.astype("i")

NameError: name 'my_float' is not defined

In [54]:
my_bool = np.array([1,0,1,0,1])
my_bool

array([1, 0, 1, 0, 1])

In [56]:
my_bool = my_bool.astype(bool)
my_bool

array([ True, False,  True, False,  True])

# session 2

In [59]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.resize(arr,(5,5))

array([[1, 2, 3, 4, 5],
       [6, 1, 2, 3, 4],
       [5, 6, 1, 2, 3],
       [4, 5, 6, 1, 2],
       [3, 4, 5, 6, 1]])

In [61]:
my_iter = [i for i in range(5)]
my_iter

[0, 1, 2, 3, 4]

In [63]:
np.fromiter(my_iter,dtype=int,count=2)

array([0, 1])

In [64]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [71]:
np.linspace(0,20,num=11,dtype="i",retstep=True) # retstep True aralık verir

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int32), 2.0)

In [74]:
np.linspace(0,[10,20],5)

array([[ 0. ,  0. ],
       [ 2.5,  5. ],
       [ 5. , 10. ],
       [ 7.5, 15. ],
       [10. , 20. ]])

In [76]:
np.linspace(0,[10,20],5,dtype="i",axis=1)

array([[ 0,  2,  5,  7, 10],
       [ 0,  5, 10, 15, 20]], dtype=int32)

In [83]:
np.logspace(1,3,num=10)

array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
         77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
        599.48425032, 1000.        ])

In [84]:
np.logspace(1,3,num=10, base=2)

array([2.        , 2.33305808, 2.72158   , 3.1748021 , 3.70349885,
       4.32023896, 5.0396842 , 5.87893797, 6.85795186, 8.        ])

In [85]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [86]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0]])

In [89]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1]])

In [90]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
np.eye(3,3,0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [100]:
np.random.rand(5,5)

array([[0.63319802, 0.48489445, 0.78168979, 0.59647087, 0.93830226],
       [0.02720206, 0.68989355, 0.5583715 , 0.04508759, 0.14378416],
       [0.22859574, 0.8537177 , 0.44451657, 0.37769382, 0.3802076 ],
       [0.900528  , 0.55293381, 0.96383467, 0.12809826, 0.14952067],
       [0.36184598, 0.05105561, 0.46296367, 0.00854422, 0.4201987 ]])

In [106]:
np.random.randint(100)

63

In [107]:
np.random.randint(1,10)

2

In [108]:
np.random.randint(1,100,10)

array([22, 59,  4, 40, 40, 23, 65, 45, 85,  9])

In [117]:
a =np.random.randint(1,100,10).reshape(5,2)
a

array([[72, 64],
       [48, 15],
       [ 7, 19],
       [69, 19],
       [13, 46]])

In [115]:
np.random.randint(1,100, size=(5,2))

array([[16, 21],
       [31,  8],
       [47, 75],
       [80, 10],
       [56,  9]])

In [119]:
a.max()

72

In [120]:
a.min()

7

In [122]:
np.sort(a,axis=0)

array([[ 7, 15],
       [13, 19],
       [48, 19],
       [69, 46],
       [72, 64]])

In [129]:
b = np.random.randint(1,10,10)
b

array([2, 5, 6, 9, 9, 8, 2, 9, 3, 3])

In [130]:
b.argmax() # en büyük sayının indexini verir

3

In [131]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
arr.size

6

In [133]:
arr.shape

(2, 3)

In [134]:
arr.itemsize

4

In [135]:
arr.itemsize * arr.size

24

In [137]:
x = arr.copy()
x

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
arr[0] = 100
arr

array([[100, 100, 100],
       [  4,   5,   6]])

In [140]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
arr.transpose()

array([[100,   4],
       [100,   5],
       [100,   6]])

# session3

In [143]:
x = np.array([1,2,3])
y = np.array([4,5,6])
xy = np.concatenate((x,y))
xy

array([1, 2, 3, 4, 5, 6])

In [144]:
a =np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [151]:
b =np.array([[5,6], [7,8]])
b

array([[5, 6],
       [7, 8]])

In [152]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [153]:
np.concatenate((a,b), axis =1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [161]:
np.split(a,2)

[array([[1, 2]]), array([[3, 4]])]

In [156]:
np.array_split(a,3)

[array([[1, 2]]), array([[3, 4]]), array([], shape=(0, 2), dtype=int32)]

In [163]:
x = np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [166]:
np.split(x,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [171]:
np.vsplit(x,[2]) #axis 0 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [170]:
np.split(x,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [172]:
np.hsplit(x,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [173]:
a = np.random.randint(0,10,10)
a

array([8, 1, 7, 6, 6, 4, 3, 3, 2, 1])

In [174]:
a.argmax()

0

In [175]:
np.sort(a)

array([1, 1, 2, 3, 3, 4, 6, 6, 7, 8])

In [185]:
np.sort(a)[::-1] #büyükten küçüğe

array([8, 7, 6, 6, 4, 3, 3, 2, 1, 1])

In [178]:
myarr = np.random.randint(1,100,(3,3))
myarr

array([[51, 29, 18],
       [53, 49, 19],
       [95, 96, 75]])

In [179]:
np.sort(myarr)

array([[18, 29, 51],
       [19, 49, 53],
       [75, 95, 96]])

In [180]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [181]:
arr[-1]

23

In [182]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [183]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [187]:
arr[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [184]:
arr[::-1]

array([23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1,  0])

In [189]:
arr[::-1][1::2]

array([22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [191]:
arr[::2][::-1]

array([22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr_2d[1]

array([4, 5, 6])

In [6]:
arr_2d[:,1]

array([2, 5, 8])

In [7]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [212]:
arr_2d[[0,2],[2,2]]

array([3, 9])

In [8]:
arr_2d[[0,2],[2]]

array([3, 9])

In [10]:
arr_2d[[2,0],[0,2]]

array([7, 3])

In [216]:
np.eye(5,6,k =1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])